/**
 * Lancaster County taxing district codes → municipality names.
 * Source: Lancaster County Recorder of Deeds + county tax inquiry ward codes.
 * @see https://www.lancasterdeeds.com/recording-information/district-codes-municipalities-school-districts
 */
module.exports = {
  '010': 'Adamstown Borough',
  '020': 'Akron Borough',
  '030': 'Bart Township',
  '040': 'Brecknock Township',
  '050': 'Caernarvon Township',
  '060': 'Christiana Borough',
  '070': 'Clay Township',
  '080': 'East Cocalico Township',
  '090': 'West Cocalico Township',
  '091': 'West Cocalico Township',
  '100': 'Colerain Township',
  '110': 'Columbia Borough',
  '120': 'Conestoga Township',
  '130': 'Conoy Township',
  '140': 'Denver Borough',
  '150': 'East Donegal Township',
  '160': 'West Donegal Township',
  '170': 'Drumore Township',
  '180': 'East Drumore Township',
  '190': 'Earl Township',
  '200': 'East Earl Township',
  '210': 'West Earl Township',
  '220': 'East Petersburg Borough',
  '230': 'Eden Township',
  '240': 'Elizabeth Township',
  '250': 'Elizabethtown Borough',
  '260': 'Ephrata Borough',
  '270': 'Ephrata Township',
  '280': 'Fulton Township',
  '290': 'East Hempfield Township',
  '300': 'West Hempfield Township',
  '310': 'East Lampeter Township',
  '320': 'West Lampeter Township',
  '330': 'City of Lancaster',
  '331': 'Lancaster City (Ward 1)',
  '332': 'Lancaster City (Ward 2)',
  '333': 'Lancaster City (Ward 3)',
  '334': 'Lancaster City (Ward 4)',
  '335': 'Lancaster City (Ward 5)',
  '336': 'Lancaster City (Ward 6)',
  '337': 'Lancaster City (Ward 7)',
  '338': 'Lancaster City (Ward 8)',
  '339': 'Lancaster City (Ward 9)',
  '340': 'Lancaster Township',
  '350': 'Leacock Township',
  '360': 'Upper Leacock Township',
  '370': 'Lititz Borough',
  '380': 'Little Britain Township',
  '390': 'Manheim Township',
  '400': 'Manheim Borough',
  '410': 'Manor Township',
  '420': 'Marietta Borough',
  '430': 'Martic Township',
  '440': 'Millersville Borough',
  '450': 'Mount Joy Borough',
  '460': 'Mount Joy Township (Upper)',
  '461': 'Mount Joy Township (Lower)',
  '470': 'Mountville Borough',
  '480': 'New Holland Borough',
  '490': 'Paradise Township',
  '500': 'Penn Township',
  '510': 'Pequea Township',
  '520': 'Providence Township',
  '530': 'Quarryville Borough',
  '540': 'Rapho Township',
  '550': 'Sadsbury Township',
  '560': 'Salisbury Township',
  '570': 'Strasburg Borough',
  '580': 'Strasburg Township',
  '590': 'Terre Hill Borough',
  '600': 'Warwick Township',
  '780': 'Lancaster City (Annexation)',
  '790': 'Lancaster City (Annexation)',
  '810': 'Lancaster City (Annexation)',
  '820': 'Lancaster City (Annexation)',
  '830': 'Lancaster City (Annexation)',
  '999': 'Unknown District',
};
